# Generated by Django 5.2.5 on 2025-08-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('livestock', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='mkulima',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='livestock', to='accounts.mkulimaprofile'),
        ),
    ]
