# Generated by Django 5.2.5 on 2025-08-31 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0002_alter_animal_mkulima'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
