# Generated by Django 5.2.5 on 2025-08-31 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livestock', '0003_animal_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='tag_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
