# Generated by Django 6.0.2 on 2026-08-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_mkulimaprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vetprofile',
            name='license_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
