# Generated by Django 5.2.5 on 2025-08-25 10:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, db_index=True, help_text='Time scheduled for consultation', null=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('SCHEDULED', 'Scheduled'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], db_index=True, default='REQUESTED', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Notes or summary after consultation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(help_text='Farmer requesting veterinary consultation', on_delete=django.db.models.deletion.CASCADE, related_name='consultations_requested', to=settings.AUTH_USER_MODEL)),
                ('vet', models.ForeignKey(blank=True, help_text='Vet assigned to handle the consultation', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'ordering': ['-scheduled_at', '-requested_at'],
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='consultatio_status_8aa8b4_idx'), models.Index(fields=['vet', 'status', 'scheduled_at'], name='consultatio_vet_id_09b8f0_idx')],
            },
        ),
    ]
