# Generated by Django 5.2.5 on 2025-08-25 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaccinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification')], db_index=True, default='SMS', max_length=20)),
                ('send_at', models.DateTimeField(db_index=True, help_text='When the notification should be sent')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('payload', models.JSONField(blank=True, help_text='Optional structured data (e.g. subject, body, metadata)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(help_text='The farmer or vet who will receive this notification', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(help_text='Vaccination schedule this notification belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vaccinations.vaccinationschedule')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-send_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'send_at'], name='notificatio_status_73a2f7_idx'), models.Index(fields=['send_at'], name='notificatio_send_at_2ebbee_idx')],
                'constraints': [models.UniqueConstraint(fields=('schedule', 'recipient', 'channel', 'send_at'), name='uniq_notification_sched_recipient_channel_sendat')],
            },
        ),
    ]
