# Generated by Django 5.2.5 on 2025-08-28 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('notifications', '0001_initial'),
        ('vaccinations', '0002_vaccine_description_vaccine_manufacturer'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='consultation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='consultations.consultation'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='schedule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='vaccinations.vaccinationschedule'),
        ),
    ]
