# Generated by Django 5.2.5 on 2025-08-28 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notification_consultation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, help_text='Optional structured data', null=True),
        ),
    ]
