# Generated by Django 5.2.5 on 2025-08-25 10:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livestock', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('dose', models.CharField(help_text='Dosage info: 2ml per 10kg bodyweight or 5ml fixed dose', max_length=100)),
                ('route', models.CharField(blank=True, choices=[('IM', 'Intramuscular (into muscle)'), ('SC', 'Subcutaneous (under skin)'), ('ORAL', 'Oral (by mouth)'), ('NASAL', 'Nasal (spray)')], help_text='How the vaccine should be administered', max_length=20)),
                ('recommended_interval_days', models.PositiveIntegerField(blank=True, help_text='Interval before next dose/booster (in days)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccineTargetSpecies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('species', models.CharField(choices=[('cattle', 'Cattle'), ('goat', 'Goat'), ('sheep', 'Sheep'), ('poultry', 'Poultry'), ('other', 'Other')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('next_due', models.DateField(db_index=True)),
                ('interval_days', models.PositiveIntegerField(help_text='Interval in days before the next dose is due')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('PAUSED', 'Paused')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_schedules', to='livestock.animal')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='vaccinations.vaccine')),
            ],
        ),
        migrations.CreateModel(
            name='VaccinationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_administered', models.DateField()),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccination_records', to='livestock.animal')),
                ('performed_by', models.ForeignKey(blank=True, help_text='Vet or staff who administered the vaccine', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_vaccinations', to=settings.AUTH_USER_MODEL)),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='vaccinations.vaccine')),
            ],
        ),
        migrations.AddField(
            model_name='vaccine',
            name='target_species',
            field=models.ManyToManyField(blank=True, related_name='vaccines', to='vaccinations.vaccinetargetspecies'),
        ),
    ]
